In [15]:
#!python
#!/usr/bin/env python
import pandas as pd 
import tables
file = tables.open_file('../data/DeepSeaTrainingData/deepsea_train/train.mat')


In [16]:
reread = pd.read_hdf('../data/DeepSeaTrainingData/deepsea_train/train.mat')

ValueError: No dataset in HDF5 file.

In [19]:
import numpy as np
import h5py

f = h5py.File('../data/DeepSeaTrainingData/deepsea_train/train.mat','r')
variables = f.items()

for var in variables:
    name = var[0]
    data = var[1]
    print( "Name ", name ) # Name
    if type(data) is h5py.Dataset:
        # If DataSet pull the associated Data
        # If not a dataset, you may need to access the element sub-items
        value = data.value
        print( value ) # NumPy Array / Value

Name  traindata


/home/narumeena/anaconda3/lib/python3.7/site-packages/h5py/_hl/dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Name  trainxdata
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 1 1]
  [0 0 0 ... 1 0 0]
  [0 0 1 ... 0 0 0]]

 [[0 0 1 ... 1 1 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 1]
  [0 0 0 ... 0 0 0]]

 [[0 0 1 ... 0 0 0]
  [0 0 0 ... 1 1 0]
  [0 0 0 ... 0 0 1]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 1 0 ... 0 0 0]
  [1 0 0 ... 1 1 0]
  [0 0 1 ... 0 0 0]
  [0 0 0 ... 0 0 1]]

 [[0 0 0 ... 0 0 1]
  [0 1 1 ... 1 0 0]
  [1 0 0 ... 0 0 0]
  [0 0 0 ... 0 1 0]]

 [[0 1 0 ... 0 0 0]
  [0 0 0 ... 1 0 0]
  [0 0 1 ... 0 0 0]
  [1 0 0 ... 0 1 1]]]
